//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "literature_vote")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub handle: String,
    pub instance: String,
    pub literature_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::literature::Entity",
        from = "Column::LiteratureId",
        to = "super::literature::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Literature,
}

impl Related<super::literature::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Literature.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
