//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::art::Entity as Art;
pub use super::art_vote::Entity as ArtVote;
pub use super::instance::Entity as Instance;
pub use super::literature::Entity as Literature;
pub use super::literature_vote::Entity as LiteratureVote;
